[package]
name = "burg_yew"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
stylist = {version = "0.13.0", features = ["yew", "parser"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
